name: build

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  go-versions:
    name: lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      latest: ${{ steps.versions.outputs.latest }}
    steps:
      - name: check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: arnested/go-version-action@v1.1.16
        id: versions

  build:
    runs-on: ${{ matrix.os }}
    needs: go-versions
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:

    - name: setup go ${{ matrix.go-version }}
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ${{ matrix.go-version }}

    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: install
      run: go install -mod=readonly ./cmd/tuplip
    
    - name: test
      run: go test -v ./...
